### ISSUE TITLE
Null safety migration

### ISSUE THREAD

**Issue by Geonjae-Joo** [OwnWeb/map_elevation#5]
hi
First, I am so thankful for what you have done here.
I am just wondering is there any plane for migrating null-safety??
or any way to use this package with null-safety version of dart and flutter?

**Comment by HugoHeneault** [comment]
Hello @Geonjae-Joo !

Thanks for your kind words. 😊 

We don't have much time these days for a null safety migration. 
If you - or anyone interested - could work on it (see [migration guide](https://dart.dev/null-safety/migration-guide)) I would review it asap. 

Have a nice day!

**Comment by HugoHeneault** [comment]
We're about to ship null safety. Could you have a try and tell us if that's ok for you?
#6
